### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by bondarau** [curityio/idsvr-helm#73]
I don't fully understand how the interaction with the configuration file works. What will happen if I make several changes and commit them one by one (a timestamp is created secretly)? What will happen if the Admin POD restarts or if I need to move it to another NODE? How will it load the latest configuration file from secrets or otherwise load the latest configuration file? Can you clarify?

**Comment by anestos** [comment]
The configuration files provided in the `curity.config.configuration` value are used to bootstrap the admin node with config. 
Any changes you make are store only in memory and are backed up only if you set `curity.config.backup` to `true. 

Although now the configuration is backed up it **is not** applied if you redeploy or if the pod is moved or restart. For that you would need to point to the backup file in `curity.config.configuration` to apply it. 

This is a design desicion because we don't want Curity users to get used to make changes in production in the Admin UI or other interfaces. We advise to use [Parametarized Configuration](https://curity.io/docs/idsvr/latest/configuration-guide/parameterized-configuration.html) and include the XML files inside the docker image you build. 

We rarely have any Curity users using the default docker image, most will create a new one with extra layers (on top of our default image) that contains template overrides, plugins, configuration, possibly log4j configuration etc, so the helm chart is following that paradigm.

If you don't want to do that, what we usually suggest is a "custom" backup script that creates a not only a "tagged" backup (named after the data and commit id as it is by default) but also a "latest" backup and that could be the one you reference in your `curity.config.configuration`. Then each time the deployment is upgraded or the pod is moved/destroyed, the configuration from the latest backup will be applied.

**Comment by bondarau** [comment]
Understood thanks

**Comment by bondarau** [comment]
https://github.com/curityio/idsvr-helm/pull/74

**Comment by bondarau** [comment]
https://github.com/curityio/idsvr-helm/tree/idsvr-0.12.14
